// Builds a Short's words.ts from a json3 transcript: one caption word per entry, placed on the cut-down
// timeline its shots.ts describes (gaps between shots are cut), with its speaker, names fixed and swears masked.
// usage: bun make-words.ts <project-dir> <transcript.json3>
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type * as ShotsModule from "../template/shots";

const MASKS: Record<string, string> = {
  fuck: "f**k",
  fucking: "f**king",
  fuckin: "f**kin",
  fucked: "f**ked",
  shit: "sh*t",
  bullshit: "bullsh*t",
  bitch: "b***h",
  bitches: "b***hes",
};
const YOUTUBE_CENSORED = "[ __ ]";
const MAX_HOLD = 0.8;

interface Json3 {
  events: { tStartMs: number; segs?: { utf8: string; tOffsetMs?: number }[] }[];
}

const [projectArg, transcriptPath] = Bun.argv.slice(2);
if (!projectArg || !transcriptPath) throw new Error("usage: bun make-words.ts <project-dir> <transcript.json3>");
const project = resolve(projectArg);
const { FILE_ZERO, SHOTS, SPEAKERS, FIXES }: typeof ShotsModule = await import(pathToFileURL(join(project, "shots.ts")).href);
const { events }: Json3 = await Bun.file(transcriptPath).json();

const spoken = events
  .flatMap((event) =>
    (event.segs ?? []).map((seg) => ({
      at: (event.tStartMs + (seg.tOffsetMs ?? 0)) / 1000 - FILE_ZERO,
      text: seg.utf8.replace(/>>/g, "").trim(),
    })),
  )
  .filter((word) => word.text && (word.text === YOUTUBE_CENSORED || !word.text.startsWith("[")));

const words: { text: string; speaker: ShotsModule.Speaker; start: number; end: number }[] = [];
let timelineStart = 0;
for (const shot of SHOTS) {
  const inShot = spoken.filter((word) => word.at >= shot.from && word.at < shot.to);
  inShot.forEach((word, i) => {
    const next = inShot[i + 1]?.at ?? shot.to;
    const start = timelineStart + word.at - shot.from;
    words.push({
      text: clean(word.text),
      speaker: SPEAKERS.find((s) => word.at >= s.from && word.at < s.to)?.speaker ?? "offCamera",
      start: round(start),
      end: round(start + Math.min(next - word.at, MAX_HOLD)),
    });
  });
  timelineStart += shot.to - shot.from;
}
if (words.length === 0) throw new Error("no transcript words fall inside the shots; check FILE_ZERO and the transcript");

await Bun.write(join(project, "words.ts"), wordsModule());
console.log(`${words.length} words, ${round(timelineStart)}s timeline`);

function clean(text: string): string {
  if (text === YOUTUBE_CENSORED) return "****";
  return text
    .replace(/[.,?!]+$/, "")
    .replace(/[a-z]+/gi, (word) => FIXES[word.toLowerCase()] ?? MASKS[word.toLowerCase()] ?? word)
    .toUpperCase();
}

function round(seconds: number): number {
  return Math.round(seconds * 1000) / 1000;
}

function wordsModule(): string {
  return `// Generated by make-words.ts. Do not edit.
import type { Speaker } from "./shots";

export const WORDS: { text: string; speaker: Speaker; start: number; end: number }[] = ${JSON.stringify(words, null, 1)};
`;
}
