// Builds a Short's captions and bleeps from YouTube's word-level auto-captions, for the moments in its segments.ts.
// Writes assets/captions.srt (one word per cue, profanity masked), bleeps.ts, and assets/sfx/bleep-track.wav
// (one timeline-long track: a 1 kHz tone inside each bleep window, silence elsewhere).
// usage: bun captions.ts <project-dir> <captions.en.json3>
import { mkdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { Bleep } from "../template/bleeps";
import type { Segment } from "../template/segments";

const PROFANITY = /fuck|shit|bitch|nigg(?:a|er)|\bass(?:hole)?\b/gi;
const YOUTUBE_CENSORED = "[ __ ]";
const CUE_MAX = 1.2;
const BLEEP_LEAD = 0.05;
const BLEEP_MIN = 0.25;
const BLEEP_MAX = 0.5;
const TONE_GAIN = 4; // ffmpeg's sine is 1/8 amplitude

interface Json3 {
  events: { tStartMs: number; segs?: { utf8: string; tOffsetMs?: number }[] }[];
}

const [projectArg, captionsPath] = Bun.argv.slice(2);
if (!projectArg || !captionsPath) throw new Error("usage: bun captions.ts <project-dir> <captions.en.json3>");
const project = resolve(projectArg);
const { SEGMENTS }: { SEGMENTS: Segment[] } = await import(pathToFileURL(join(project, "segments.ts")).href);
const { events }: Json3 = await Bun.file(captionsPath).json();

const words = events.flatMap((event) =>
  (event.segs ?? [])
    .map((seg) => ({ at: (event.tStartMs + (seg.tOffsetMs ?? 0)) / 1000, text: seg.utf8.replace(/>>/g, "").trim() }))
    .filter((word) => word.text && (word.text === YOUTUBE_CENSORED || !word.text.startsWith("["))),
);

const cues: { from: number; to: number; text: string }[] = [];
const bleeps: Bleep[] = [];
let timelineStart = 0;
for (const segment of SEGMENTS) {
  const from = segment.fileZero + segment.sourceIn;
  const to = segment.fileZero + segment.sourceOut;
  const spoken = words.filter((word) => word.at >= from && word.at < to);
  spoken.forEach((word, i) => {
    const next = spoken[i + 1]?.at ?? to;
    const text = censor(word.text);
    cues.push({ from: timelineStart + word.at - from, to: timelineStart + Math.min(next, word.at + CUE_MAX) - from, text });
    if (text === word.text) return;
    const start = word.at - BLEEP_LEAD;
    bleeps.push({
      rank: segment.rank,
      sourceTime: round(start - segment.fileZero),
      timelineTime: round(timelineStart + start - from),
      duration: round(Math.min(Math.max(next - start, BLEEP_MIN), BLEEP_MAX)),
    });
  });
  timelineStart += segment.sourceOut - segment.sourceIn;
}
if (cues.length === 0) throw new Error("no caption words fall inside the segments; check fileZero and the captions file");

await Bun.write(join(project, "assets", "captions.srt"), cues.map((cue, i) => `${i + 1}\n${timestamp(cue.from)} --> ${timestamp(cue.to)}\n${cue.text}\n`).join("\n"));
await Bun.write(join(project, "bleeps.ts"), bleepsModule(bleeps));
renderBleepTrack(join(project, "assets", "sfx"), timelineStart);
console.log(`${cues.length} cues, ${bleeps.length} bleeps, ${round(timelineStart)}s timeline`);

function censor(text: string): string {
  if (text === YOUTUBE_CENSORED) return "****";
  return text.replace(PROFANITY, mask);
}

// fuck → f**k, bitch → b***h, ass → a**: first letter kept, last letter too when the word is long enough to stay readable.
function mask(word: string): string {
  const last = word.length > 3 ? word.at(-1)! : "";
  return word[0] + "*".repeat(word.length - 1 - last.length) + last;
}

function round(seconds: number): number {
  return Math.round(seconds * 1000) / 1000;
}

function timestamp(seconds: number): string {
  const ms = Math.round(seconds * 1000);
  const pad = (n: number, width = 2) => String(n).padStart(width, "0");
  return `${pad(Math.floor(ms / 3_600_000))}:${pad(Math.floor(ms / 60_000) % 60)}:${pad(Math.floor(ms / 1000) % 60)},${pad(ms % 1000, 3)}`;
}

function bleepsModule(bleeps: Bleep[]): string {
  return `// Generated by captions.ts. Do not edit.
export interface Bleep {
  rank: number;
  /** Start in the clip file's own time, where volume keyframes live. */
  sourceTime: number;
  timelineTime: number;
  duration: number;
}

export const BLEEPS: Bleep[] = ${JSON.stringify(bleeps, null, 2)};
`;
}

function renderBleepTrack(folder: string, duration: number): void {
  mkdirSync(folder, { recursive: true });
  const windows = bleeps.map((bleep) => `between(t,${bleep.timelineTime},${round(bleep.timelineTime + bleep.duration)})`);
  const audible = windows.length > 0 ? windows.join("+") : "0";
  const ffmpeg = Bun.spawnSync([
    "ffmpeg", "-v", "error", "-y",
    "-f", "lavfi", "-i", `sine=frequency=1000:duration=${round(duration)}`,
    "-af", `volume=${TONE_GAIN},volume=0:enable='not(${audible})'`,
    join(folder, "bleep-track.wav"),
  ]);
  if (ffmpeg.exitCode !== 0) throw new Error(`ffmpeg failed: ${ffmpeg.stderr.toString()}`);
}
