// Generated by captions.ts. Do not edit.
export interface Bleep {
  rank: number;
  /** Start in the clip file's own time, where volume keyframes live. */
  sourceTime: number;
  timelineTime: number;
  duration: number;
}

export const BLEEPS: Bleep[] = [];
